name: Test

on:
  push:
    branches: 'master'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run_test:
    name: Test
    runs-on: ubuntu-18.04
    env:
      MY_RUBY_VERSION: 2.5.0
      RUBY_RAILS_VERSION: 5.2.3
    timeout-minutes: 5
    if: |
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]') &&
      github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@master
      - name: Npm Install
        shell: bash
        run: |
          npm install hubot@2.19.0
          npm install
      - name: Run build script
        shell: bash
        run: |
          ./script/test
